### ISSUE TITLE
this is boring

### ISSUE THREAD

**Issue by Wolfkid200444** [ItsSxR/air-fetch#1]

**Comment by ItsSxR** [comment]
Hi,

You clearly are confused as to how to use Javascript. This package is here to assist developers when fetching an airline or airport.

Please learn to code JS before submitting any packages.

**Comment by Wolfkid200444** [comment]
I love u 



lol

**Comment by Wolfkid200444** [comment]
idk whats wrong with me but im sorry
SxR
